### Numpy basic API training (summary)

#### __Reviews__

* __numpy.array(')__ : n-dimensional array 생성
  
* __numpy.array(').dtype__ : array 내 원소의 data type
* __type(A)__ : A의 data type
* __numpy.array(').shape__ : array의 size
* __numpy.array(').ndim__ : array의 dimension (.shape의 length)
* __numpy.array(').astype(')__ : array 내 원소의 data type 변환
* __numpy.array(') .sum / .min / .max / .mean / .std__ : array 내 원소에 대한 기초 통계. 파라미터 값으로 axis = 0 -> 행 기준, axis = 1 -> 열 기준 계산
* __numpy.arange(')__ : numpy array에서의 list(range('))
* __numpy.zeros(tuple,dtype = ')__ : 모든 원소를 0으로 갖는 tuple size의 array 생성
* __numpy.ones(tuple,dtype = ')__ : 모든 원소를 1로 갖는 tuple size의 array 생성
* __numpy.array(').reshape(row,col)__ : array를 reshape의 row, col 크기로 재구성. .reshape(-1,)은 보통 matrix to vector로 하기위해 많이 쓰임.
* __numpy indexing and slicing__ : list 자료형과 동일하나 fancy indexing, boolean indexing이 자유자재로 가능
* __numpy.sort(A)__ : array A를 정렬. axis = 여부에 따라 행축정렬 또는 열축정렬 가능. python의 sorted(') 와 유사
* __numpy.array(A).sort()__ : array A를 정렬하는 것은 같으나 python의 list.sort()와 같음.
* __numpy.argsort(A)__ : A가 정렬이 적용된 array일때 A가 정렬되기 전의 index를 반환
* __numpy.dot(A,B)__ : A와 B에 대한 inner product
* __numpy.array(A).transpose()__ : array A의 전치

In [1]:
# import numpy package
import numpy as np

In [2]:
# generate ndarray (n-dimensional array)
a = list(range(1,11))
A = np.array(a)
print('numpy array: ',A)

numpy array:  [ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# the type of the variable
print(type(a))
print(type(A))
# the type of the elements (only numpy)
print(A.dtype)

<class 'list'>
<class 'numpy.ndarray'>
int32


In [4]:
# the shape and dimension of ndarray
print('shape: ',A.shape)
print('dimension: ',A.ndim)

shape:  (10,)
dimension:  1


In [5]:
# transformation of the type of the elements
strings = np.array(['1','2','3','4'])
print(strings.dtype)
print(strings.astype('float64')) # float
print(strings.astype('int32')) # int

<U1
[1. 2. 3. 4.]
[1 2 3 4]


In [6]:
# ndarray methods
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(A) # 2-dim array
print(A.sum()) # sum of all elements
print(A.sum(axis = 1)) # sum (column)
print(A.sum(axis = 0)) # sum (row)
print(A.min(axis = 0)) # minimum
print(A.max(axis = 1)) # maximum
print(A.mean(axis = 0)) # average
print(A.std(axis = 1)) # standard deviation

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[ 6 15 24]
[12 15 18]
[1 2 3]
[3 6 9]
[4. 5. 6.]
[0.81649658 0.81649658 0.81649658]


In [7]:
# generate the pre-allocation vector or basic array
A = np.arange(11) # sequence (== range() in python)
print(A)
A = np.zeros((3,3),dtype = 'int32') # zero matrix (pre-allocation)
print(A)
A = np.ones((2,3),dtype = 'int32') # the matrix filled with 1
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


In [8]:
# convert the matrix size: reshape()
A = np.arange(1,11) # 1x10 vector
print(A.reshape(2,5)) # 2x5 matrix
print(A.reshape(2,5).reshape(-1,)) # reshape(-1,): 2d array -> 1d array 
# -1 is the pivot.
print(A.reshape(-1,2)) # fix the column size = 2 and resize automatically

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [9]:
'''
NOTE)
Numpy indexing and slicing are the same as python built-in, but fancy indexing & boolean indexing is possible in numpy.

Also note that the slicing [::-1] means that reverse the elements for given array.
'''
A = np.arange(1,11)
print(A) # 1x10 vector
print(A[[0,2,4]]) # fancy indexing
print(A > 5) # boolean indexing
print(A[A > 5]) # filtering using boolean indexing
print(A[::-1]) # the elements are reversed

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


In [10]:
# sorting methods for ndarray
A = np.array([5,3,2,8,1,6,7,7,0])
print(A) # 1x10 vector
print(np.sort(A)) # sort A
print(A.sort()) # return 'None'

A = np.array([5,3,2,8,1,6,7,7,0])
print(A) # original
A.sort()
print(A) # sorted array

A = np.array([5,3,2,8,1,6,7,7,0]).reshape(3,3) # 3x3 matrix
print(np.sort(A,axis = 0)) # sort based on row

A = np.array([5,3,2,8,1,6,7,7,0])
print(np.sort(A))
# argsort: return the original index of the sorted array
print(np.argsort(A))

[5 3 2 8 1 6 7 7 0]
[0 1 2 3 5 6 7 7 8]
None
[5 3 2 8 1 6 7 7 0]
[0 1 2 3 5 6 7 7 8]
[[5 1 0]
 [7 3 2]
 [8 7 6]]
[0 1 2 3 5 6 7 7 8]
[8 4 2 1 0 5 6 7 3]


In [11]:
A = np.zeros((2,3))
B = np.ones((3,2))
print('inner product:\n',np.dot(A,B)) # inner product

inner product:
 [[0. 0.]
 [0. 0.]]


In [12]:
A = np.array([5,3,2,8,1,6,7,7,0]).reshape(3,3)
print(A) # the original
print(A.transpose()) # transpose of A

[[5 3 2]
 [8 1 6]
 [7 7 0]]
[[5 8 7]
 [3 1 7]
 [2 6 0]]
